// Copyright (c) luaugo contributors. Licensed under the MIT License.

// Command swarm demonstrates running thousands of independent Luau VMs
// concurrently across Go goroutines. Each VM is fully isolated --
// separate stack, separate globals, separate GC -- so they can scale
// linearly with available CPU cores without any cross-state locking.
//
// What it does:
//   - Compile a script once on the main goroutine (the compiler is
//     stateless, so the same bytecode blob is safely shared).
//   - Fan out N workers, each owning a private vm.State.
//   - Stream a stream of jobs (one int each) through a channel; each
//     worker resumes its VM with the job as a vararg, collects the
//     return value, and reports back.
//   - Print a histogram + wallclock so you can compare against a
//     single-threaded baseline.
//
// Run with:
//
//	go run ./docs/examples/swarm              # defaults: 1000 VMs, 100k jobs
//	go run ./docs/examples/swarm -vms 5000 -jobs 1000000
//	go run ./docs/examples/swarm -baseline    # single-VM comparison
package main

import (
	"flag"
	"fmt"
	"log"
	"runtime"
	"sync"
	"sync/atomic"
	"time"

	"github.com/one-two-three-four-five-six-seven/luaugo/pkg/compiler"
	"github.com/one-two-three-four-five-six-seven/luaugo/pkg/vm"
	"github.com/one-two-three-four-five-six-seven/luaugo/pkg/vm/lib"
)

// Workload script. Receives a seed integer via `...` and computes an
// FNV-1a-style 32-bit hash over a generated byte sequence, then folds
// it through several rounds of bit-mixing. Pure integer/bitwise work
// is exactly the kind of code where luaugo's VM should scale linearly
// across cores -- no string allocation in the hot loop, no FP, no
// stdlib calls beyond bit32 (which fastcalls).
//
// Tuning knobs:
//   - INNER: bytes hashed per job; ~4 KiB keeps each call in the
//     low-millisecond range.
//   - ROUNDS: additional bit-mix passes after the byte loop; lets us
//     bias the workload toward dispatch (cheap loop body) vs.
//     allocation (string.format below).
//
// Returns the final hash as a number plus a short label string so the
// host has something both numeric and string-typed to checksum.
//
// Note: this is a regular Go double-quoted string with explicit \n
// escapes rather than a backtick raw literal because the workload
// source contains backticks inside Lua comments and identifiers,
// which would terminate a Go raw string mid-snippet.
const script = "" +
	"local n = ...\n" +
	"local INNER = 4096\n" +
	"local ROUNDS = 8\n" +
	"\n" +
	"-- FNV-1a 32-bit constants. bit32.band keeps the accumulator in\n" +
	"-- the uint32 range regardless of how Luau widens during the loop.\n" +
	"local FNV_OFFSET = 2166136261\n" +
	"local FNV_PRIME  = 16777619\n" +
	"local MASK32     = 0xFFFFFFFF\n" +
	"\n" +
	"local h = FNV_OFFSET\n" +
	"\n" +
	"-- Byte loop: synthesize each byte from the seed and the index so\n" +
	"-- the workload depends on the seed (forcing the interpreter to\n" +
	"-- actually execute the loop instead of folding to a constant).\n" +
	"for i = 1, INNER do\n" +
	"    local b = bit32.band(i * 2654435761 + n, 0xFF)\n" +
	"    h = bit32.bxor(h, b)\n" +
	"    h = bit32.band(h * FNV_PRIME, MASK32)\n" +
	"end\n" +
	"\n" +
	"-- A few rounds of Murmur3 fmix32-style mixing so the bit pattern\n" +
	"-- fully diffuses. Each round is 5 bit32 ops; all of bit32.* fastcalls.\n" +
	"-- These constants are the canonical fmix32 multipliers (Murmur3) --\n" +
	"-- they avoid the absorbing-zero fixed point that bare xorshift hits\n" +
	"-- when h * mul mod 2^32 collapses to 0.\n" +
	"for _ = 1, ROUNDS do\n" +
	"    h = bit32.bxor(h, bit32.rshift(h, 16))\n" +
	"    h = bit32.band(h * 0x85ebca6b, MASK32)\n" +
	"    h = bit32.bxor(h, bit32.rshift(h, 13))\n" +
	"    h = bit32.band(h * 0xc2b2ae35, MASK32)\n" +
	"    h = bit32.bxor(h, bit32.rshift(h, 16))\n" +
	"    -- Re-seed with FNV_OFFSET if we hit the zero fixed point so\n" +
	"    -- the next round produces useful entropy. This branch is\n" +
	"    -- effectively never taken for real inputs but keeps the demo\n" +
	"    -- visually informative.\n" +
	"    if h == 0 then h = FNV_OFFSET end\n" +
	"end\n" +
	"\n" +
	"local label = string.format(\"job-%08x\", h)\n" +
	"return h, label\n"

func main() {
	vmCount := flag.Int("vms", 1000, "number of concurrent VMs (worker pool size)")
	jobCount := flag.Int("jobs", 100000, "total jobs to process")
	baseline := flag.Bool("baseline", false, "also run a single-VM baseline for comparison")
	verbose := flag.Bool("v", false, "print first few job results for sanity-check")
	flag.Parse()

	if *vmCount < 1 || *jobCount < 1 {
		log.Fatal("vms and jobs must both be positive")
	}
	if *vmCount > *jobCount {
		*vmCount = *jobCount // no point in having idle workers
	}

	// Compile once. The bytecode blob is pure data and is safe to
	// share across goroutines -- each VM loads its own private copy
	// of the closure tree, no aliasing.
	blob, err := compiler.CompileBinary("=worker", []byte(script), compiler.Defaults())
	if err != nil {
		log.Fatalf("compile: %v", err)
	}
	if len(blob) > 0 && blob[0] == 0 {
		log.Fatalf("compile: %s", blob[1:])
	}

	fmt.Printf("luaugo swarm demo\n")
	fmt.Printf("  GOMAXPROCS=%d  vms=%d  jobs=%d\n",
		runtime.GOMAXPROCS(0), *vmCount, *jobCount)

	// --------------------------------------------------------------
	// Parallel run
	// --------------------------------------------------------------
	parallelStart := time.Now()
	parResults := runSwarm(blob, *vmCount, *jobCount, *verbose)
	parallelDur := time.Since(parallelStart)

	fmt.Printf("\n[parallel] %d jobs across %d VMs: %v (%.0f jobs/sec)\n",
		*jobCount, *vmCount, parallelDur, float64(*jobCount)/parallelDur.Seconds())
	fmt.Printf("           checksum=%d (XOR of label hashes; should match baseline)\n",
		parResults.checksum)

	// --------------------------------------------------------------
	// Optional single-VM baseline
	// --------------------------------------------------------------
	if *baseline {
		baselineStart := time.Now()
		baseResults := runBaseline(blob, *jobCount, *verbose)
		baselineDur := time.Since(baselineStart)

		fmt.Printf("\n[baseline] %d jobs on 1 VM:    %v (%.0f jobs/sec)\n",
			*jobCount, baselineDur, float64(*jobCount)/baselineDur.Seconds())
		fmt.Printf("           checksum=%d\n", baseResults.checksum)

		speedup := float64(baselineDur) / float64(parallelDur)
		fmt.Printf("\nspeedup: %.2fx\n", speedup)
		if baseResults.checksum != parResults.checksum {
			log.Fatalf("checksum mismatch: parallel=%d baseline=%d", parResults.checksum, baseResults.checksum)
		}
	}
}

// swarmResults aggregates what we want to confirm at the end: a
// hash that proves both paths computed the same answers, and a count.
type swarmResults struct {
	jobsDone uint64
	checksum uint64
}

// runSwarm spawns vmCount workers, each owning its own vm.State, and
// feeds them jobCount jobs through a channel. Returns once every
// worker has drained the queue.
func runSwarm(blob []byte, vmCount, jobCount int, verbose bool) swarmResults {
	jobs := make(chan int, vmCount*4)

	// Feeder goroutine: pushes 1..jobCount and closes the channel
	// when done so workers see EOF and exit cleanly.
	go func() {
		for i := 1; i <= jobCount; i++ {
			jobs <- i
		}
		close(jobs)
	}()

	var (
		wg       sync.WaitGroup
		done     uint64
		checksum uint64 // bit-XOR of per-job label-hash + acc bits
	)

	// Worker goroutines. Each one creates ONE State, then loops on
	// the jobs channel. Reusing the state across jobs is much
	// cheaper than allocating per-job (Load+PCall reuses the same
	// stack, no GC pressure from spinning up arenas).
	for w := 0; w < vmCount; w++ {
		wg.Add(1)
		go func(workerID int) {
			defer wg.Done()
			s := vm.NewState()
			defer s.Close()
			lib.OpenAll(s)

			for n := range jobs {
				acc, label, ok := runJob(s, blob, n)
				if !ok {
					return
				}
				// Combine into the running checksum lock-free so
				// the comparison with baseline is order-independent.
				// sync/atomic exposes Add/Or/And but no Xor on
				// uint64, so we CAS-loop it manually.
				h := hashLabel(label) ^ uint64(int64(acc))
				for {
					cur := atomic.LoadUint64(&checksum)
					if atomic.CompareAndSwapUint64(&checksum, cur, cur^h) {
						break
					}
				}
				if v := atomic.AddUint64(&done, 1); verbose && v <= 3 {
					fmt.Printf("  worker %d -> job %d: hash=%#08x label=%s\n",
						workerID, n, uint32(acc), label)
				}
			}
		}(w)
	}
	wg.Wait()

	return swarmResults{jobsDone: done, checksum: checksum}
}

// runBaseline does the same work on a single state, sequentially.
// Useful for measuring the parallel speedup and verifying both paths
// produce the same checksum.
func runBaseline(blob []byte, jobCount int, verbose bool) swarmResults {
	s := vm.NewState()
	defer s.Close()
	lib.OpenAll(s)

	var checksum uint64
	for n := 1; n <= jobCount; n++ {
		acc, label, ok := runJob(s, blob, n)
		if !ok {
			break
		}
		checksum ^= hashLabel(label) ^ uint64(int64(acc))
		if verbose && n <= 3 {
			fmt.Printf("  baseline job %d: hash=%#08x label=%s\n", n, uint32(acc), label)
		}
	}
	return swarmResults{jobsDone: uint64(jobCount), checksum: checksum}
}

// runJob executes the worker script once with `n` as its single
// vararg, returning the script's two-value tuple. The state's stack
// is reset to its previous depth on exit so the next call starts
// from a clean slate; no per-job allocations are required.
//
// Returns (hash, label, ok). The hash is a 32-bit FNV-1a-derived
// integer wrapped in a float64 (Luau's number tag); the label is the
// hex-formatted version of it.
func runJob(s *vm.State, blob []byte, n int) (float64, string, bool) {
	if err := s.Load("=worker", blob, 0); err != nil {
		log.Printf("load: %v", err)
		return 0, "", false
	}
	base := s.Top() - 1
	s.PushInteger(int64(n))
	if status := s.PCall(1, -1, 0); status != vm.StatusOK {
		msg, _ := s.ToString(-1)
		log.Printf("job %d: %s", n, msg)
		s.SetTop(base)
		return 0, "", false
	}
	hash, _ := s.ToNumber(base + 1)
	label, _ := s.ToString(base + 2)
	s.SetTop(base) // drop the returns so the next iteration starts clean
	return hash, label, true
}

// hashLabel folds a string into a uint64 via FNV-1a. Inlined to keep
// the demo a single file and avoid adding hash/fnv as an import.
func hashLabel(s string) uint64 {
	const (
		fnvOffset = 14695981039346656037
		fnvPrime  = 1099511628211
	)
	h := uint64(fnvOffset)
	for i := 0; i < len(s); i++ {
		h ^= uint64(s[i])
		h *= fnvPrime
	}
	return h
}
